### ISSUE TITLE
Cant Access secure items (e.g. webmap)  via app login to ArcGIS online

### ISSUE THREAD

**Issue by dstubbins** [Esri/resource-proxy#124]
I have been using the DOTNET version, and failing to access secure webmaps using an app login to arcgis online, using a specific account. I noticed a closed issue https://github.com/Esri/resource-proxy/pull/109 so maybe Its a doc/config issue on my  part..

I believe the proxy is incorrectly trying to exchange a portal token for a server token from portal after getting a valid portal token.  It should just be using the portal token to access content items.  log entries below (access token edited)

My config looks like

<serverUrl url="http://techresearch.maps.arcgis.com/sharing/rest/"
                   matchAll="true"
           clientId="XYZ"
                   clientSecret="321"/>
.
LOG
'''Information: 0 : 2014-06-06 17:36:38 http://techresearch.maps.arcgis.com/sharing/rest/portals/self?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback
w3wp.exe Information: 0 : 2014-06-06 17:36:38 Matching credentials found in configuration file. OAuth 2.0 mode: True
w3wp.exe Information: 0 : 2014-06-06 17:36:38 Service is secured by https://www.arcgis.com/sharing/oauth2/: getting new token...
w3wp.exe Information: 0 : 2014-06-06 17:36:38  Token obtained: xxxxxxxxxxxm..
w3wp.exe Information: 0 : 2014-06-06 17:36:38  **Exchanging Portal token for Server-specific token for http://techresearch.maps.arcgis.com/sharing/rest...**
w3wp.exe Error: 0 : 2014-06-06 17:36:38  Token cannot be obtained: {"error":{"code":400,"message":"Unable to generate token","details":["Unable to generate token for this server"]}}'''

**Comment by jakc** [comment]
FAQ:
*Applications using appId/appSecret by design don't have permission to search for private content, even if owned by the same person.*

Proxy Config Settings:
https://github.com/Esri/resource-proxy/blob/master/README.md#proxy-configuration-settings
*If AppID is used to access hosted services, the service(s) must be owned by the user accessing it*

Ive created an app and registered with AGO.
This app consumes a public shared webmap which has one public esri basemap and one 'shared to organisation' hosted feature service.  I was hoping that I could allow public users of the app to be able to see the hosted feature service without logging in or making feature service public.  Is this possible?
