### ISSUE TITLE
Update readme's about "ping"

### ISSUE THREAD

**Issue by bsvensson** [Esri/resource-proxy#181]
See #144 and #131 which added "ping" capability for easy testing.

**Comment by slead** [comment]
The proxy.php file is working correctly for me, but I can't get the ?ping to work.

https://github.com/Esri/resource-proxy/blob/master/PHP/README.md says "Test that the proxy is installed and available: http://[yourmachine]/PHP/proxy.php?ping" but this just returns 403:

"The proxy tried to resolve a URL that was not found in the configuration file....."

I also can't see "ping" anywhere inside proxy.php. Thanks for any advice.

**Comment by bsvensson** [comment]
@slead - The ping capability was added on November 26, 2014 - see the commit history https://github.com/Esri/resource-proxy/commits/master/PHP/proxy.php

**Comment by slead** [comment]
@bsvensson thanks. it's a bit confusing because https://github.com/Esri/resource-proxy recommends the released version, but this doesn't include the ping

"Instructions: Download and unzip the .zip file or clone the repository. You can download a released version (recommended) or the most recent daily build."

**Comment by jgravois** [comment]
i agree.  we should probably either tag a new release or remove the instructions from the documentation.

**Comment by slead** [comment]
FWIW I think the ping is a good way to verify that it's working. Thanks guys
