### ISSUE TITLE
App Login does not work with Portal for ArcGIS 10.3

### ISSUE THREAD

**Issue by orossini** [Esri/resource-proxy#208]
Trying to access a webmap containing basemap and a feature layer fails.
The access is granted to the webmap (and if the basemap is not secured it is loaded), but when the app tries to load the feature layer, the access to the feature layer is denied: {"error":{"code":498,"message":"Invalid Token","details":[]}}
Any access to a Portal 10.3 hosted webservice is denied with the same error.

Has anyone tested it on Portal 10.3?
Is anyone having the same problem?
Any thought on this is welcome.
Thanks

**Comment by hgonzago** [comment]
@orossini - which proxy are you using?

Also, you may want to take a look at an existing issue, #198 

Does this look familiar?

**Comment by orossini** [comment]
Thanks for your answer.

I'm using the DotNet proxy.
Please also note that I'm using Portal / ArcGIS Server 10.3.
(I've tested the proxy with ArcGIS Online and it works perfectly)
The issue is that the service used in the webmap cannot be accessed. It ends with a Invalid token error. the token is generated but is invalid.
so the access to the secure webmap is granted but any private ArcGIS server webservice embedded in the webmap raised this error. So the Login dialog box appears asking to the user to log in in order to access the service.
I've tried to comment out the lines as specified in the issue #198 but it doesn't solve this problem.
I have also tried to run the ashx in debug mode (with Visual Studio): averything seems to be fine except that the generated token is not valid. 
I'm wondering if the token is generated from the correct end point, and if there is a mismatch between Portal OAuth endpoint and ArcGIS Server token endpoint.

**Comment by hgonzago** [comment]
@bsvensson @afili @jgravois 

including you three in this as I haven't tested this on Portal 10.3 yet. Anyone tried this?

**Comment by afili** [comment]
I have tested with a Portal Federated with ArcGIS Server 10.3 and it works for me. There was an issue with 10.3 where the proxy was trying to send a request to generate the token using the GET method and ArcGIS Server 10.3 would not allow it since it was expecting POST. @esoekianto fixed it and submitted a pull request which is merget but the fix is not included in the released version yet. It can be found at https://github.com/Esri/resource-proxy by clicking the "Download ZIP". Not sure if it is the same issue since we were getting 400 and not 498 but it is worth trying this version.

**Comment by bsvensson** [comment]
Closing - based on @afili comment from 2015-02-26.
