### ISSUE TITLE
PHP specific: Proxying attachments does not carry over token

### ISSUE THREAD

**Issue by hgonzago** [Esri/resource-proxy#221]
@phpmaps - assigned this to you as I know you may want to know about this. Solomon found this issue.

This happens on PHP, works fine with .NET (didn't test JSP).

Using the following code you should notice that if you click on a feature with an attachment, the attachment does not come across. The attachment is proxied, but the token never gets appended to the attachment info, therefore causing token errors. Try the same code using a .NET proxy and it works.

```javascript

<!DOCTYPE html>
<html>
<head>
<title>Create a Map</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no">
<link rel="stylesheet" href="http://js.arcgis.com/3.13/dijit/themes/claro/claro.css">
<link rel="stylesheet" href="http://js.arcgis.com/3.13/esri/css/esri.css">
<style>
html, body, #mapDiv{
padding: 0;
margin: 0;
height: 100%;
}
</style>

<script src="http://js.arcgis.com/3.13/"></script>
<script>

require(["esri/map", "esri/urlUtils", "esri/dijit/PopupTemplate", "esri/layers/FeatureLayer", "dojo/domReady!"], function(Map,urlUtils, PopupTemplate, FeatureLayer) {

urlUtils.addProxyRule({
urlPrefix: "services.arcgis.com/V6ZHFr6zdgNZuVG0/",
proxyUrl: "http://heatherg.esri.com/proxy/proxy.php"
});

var map = new Map("mapDiv", {
center:  [-122.385 ,37.770],
zoom: 17,
basemap: "streets"
});

//var layer = new FeatureLayer("http://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure/FeatureServer/0");
var layer = new FeatureLayer("http://services.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/SF_Street_Tree_Locations/FeatureServer/0",{
outFields: ["*"],
infoTemplate: new PopupTemplate({
title: "Attachments",
description: "{PlantDate}",
showAttachments:true
})
});
map.addLayer(layer);
});
</script>

</head>
<body class="claro">
<div id="mapDiv"></div>
</body>
</html>

```

**Comment by bsvensson** [comment]
@hgonzago - is this specific to secured services? Or more generic when doing file attachments with php proxy?

**Comment by phpmaps** [comment]
@hgonzago @bsvensson this sounds like a regression.  Using our JSAPI attachment sample was heavily tested before the PHP proxy got released and during several updates.  I am seeing wonky behavior in a quick PHP proxy test (which may be a versions old).   For some reason I now see the file's path showing up in the attachment within the service.  Local paths should not be included in the file name.  

![image](https://cloud.githubusercontent.com/assets/2159502/9073369/c7a8d07e-3ab5-11e5-9061-eacf729c7866.png)

**Comment by phpmaps** [comment]
Passing token seems fixable.  However, it's super strange that the file path gets included in the upload right?  I am thinking PHP cURL may have some quirks here. 

Standard cURL does the job correctly.

```
curl -F "f=json" -F "filename=ajax-loader.gif" -F "attachment=@/Users/doogle/downloads/ajax-loader.gif" http://sampleserver6.arcgisonline.com/arcgis/rest/services/SF311/FeatureServer/0/644673/addAttachment

```

**Comment by phpmaps** [comment]
Does anyone else see the path get appended to the file name in the attachment viewer?

**Comment by phpmaps** [comment]
The content type of the response is derived from the info file's mime type. If the mime type can't be derived, the response content type will be set to application/octet-stream.

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r30000007m000000

When looking at uploaded files via php proxy the content-type is always this.  

```
{"attachmentInfos":[{"id":115302,"contentType":"application/octet-stream","size":2044,"name":"/private/var/tmp/android.png"}]}
```

**Comment by phpmaps** [comment]
@bsvensson  @jgravois @hgonzago  - Update on this one.   I think this may be an issue inside server core where server core cannot discern the content type and file name from a PHP cURL upload.  PHP gets the file to the server and my suspicion is that server does not handle the file all that well and defaults to thinking it's application/octet-stream and does not pick up the filename.  The specific issue with the token not getting passed  I think can be fixed but it's not going to solve the general awkwardness surrounding file attachments. 

attachment : The file to be uploaded as a new feature attachment. The content type, size, and name of the attachment ```will be derived from the uploaded file```.

Hopefully someone who wrote the API for addAttachment could look at this.  I suspect the problem is in server and how it reads the boundary.  That's my best guess.  Also just to note, I did some testing using php's move_uploaded_file before POSTing the file (which is a common practice) and I still see the full file path in the file name and the content type is not being detected.  

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r3000000wt000000

Alternatively this could be an issue my own PHP curl extension.  To troubleshoot that I would ask someone with a PHP curl extension tell me the behavior when they addAttachment to a non-secured feature service.  Does the attachment viewer capture the full path in the file name?

**Comment by phpmaps** [comment]
@bsvensson @hgonzago  - Guys is there someone I can talk to knows the addAttachment API in server?

~Hopefully someone who wrote the API for addAttachment could look at this..

**Comment by hgonzago** [comment]
@phpmaps if the issue is on the server end how is it that it works ok outside of the PHP proxy?

**Comment by phpmaps** [comment]
@hgonzago - So PHP gets the file to the server just like Java, NET and JS can.   I can even do this with cURL.  There is something strange with PHP uploads.  Our server is not cannot picking up

1) the content type 
2) the file name from a PHP cURL upload

The best I can tell that info is being sent.

Also just to recap this happens with secure and non-secure services accepting file uploads.  If we know someone who knows wireshark that may help. On a wireshark machine I can get PHP up and running but really need help when it comes to interpreting packets.  Alternatively if we can get the dev who wrote the addAttachment to set a breakpoint when server gets the file upload that should uncover a few things to.  I am up for other ideas the help get this bug marked as resolved.
