### ISSUE TITLE
Proxy seems not getting authorization token.

### ISSUE THREAD

**Issue by bigend** [Esri/resource-proxy#231]
I am using proxy page for .net with application pool for .net 4 and ArcGIS server 10.2. My proxy configuration serverUrl tag is like this:

        <serverUrl url="http://myServer/ags/rest/services"
                   matchAll="false" username="myName" password="myPass" />

I am sure that username and password are correct (checked with ...tokens/generateToken web interface and succesfully get token). However when I try access my secured service (http://myserver/DotNetProxy/proxy.ashx?http://myserver/ags/rest/services/myService/?f=pjson) I am allways getting this error:

{
 "error": {
  "code": 499,
  "message": "Token Required",
  "details": []
 }
}
Unsecured services are answering without problem. Any help, hint, clue or anything would be very appreciated.

**Comment by afili** [comment]
Are you using proxy version 1.1 beta (you can check that in the beginning of the proxy.ashx file). If yes, you can use a log file that will print out the tokenResponse from the server. This way you will be able to check if you get a valid token or if you get an error. In order to do so, you first need to use a logFile in the proxy.config (e.g. <ProxyConfig allowedReferers="*" mustMatch="true" logFile="log.txt">) and then add this line of code logMessageToFile("This is the tokenResponse from the server: " + tokenResponse);  in the proxy.ashx, in the method getNewTokenIfCredentialsAreSpecified and below the line string tokenResponse = webResponseToString(doHTTPRequest(uri, "POST"));

**Comment by bigend** [comment]
@afili thank you very much, it helped a lot. I finally realized that in proxy.config I had matchAll="false" and url="http://myServer/ags/rest/services", and I was testing proxy with url : http://myServer/ags/rest/services?f=pjson. The problem was ?f=pjson parameter. In  GetConfigServerUrl method the uri parts are compared and uri in config has 5 parts and uri in my testing url had 6 parts (thanks to f=pjson parameter). I just didn't realized that format parameter will collide with matchAll="false". Thank you for help one more time.
