### ISSUE TITLE
Unable to access html endpoint for ArcGIS Online hosted feature services

### ISSUE THREAD

**Issue by david-chambers** [Esri/resource-proxy#302]
When accessing the html endpoint for a ArcGIS Online hosted feature service that is not shared publicly I receive the error: 'Token Required' and 'http://<machine name>/ESRI.ArcGIS.SDS.REST.css Failed to load resource: the server responded with a status of 404 (Not Found)' is printed to the console.  When changing the endpoint to json or pjson i can view the service information successfully.

![proxy_html](https://cloud.githubusercontent.com/assets/13684989/10226571/33e14110-6836-11e5-9243-1272198a5d87.jpg)

**Comment by jgravois** [comment]
we're calling this 'by design' because the HTML fetched by the end resource includes relative links to supporting CSS which haven't been fetched.

for application support, JSON support is all that's required and these requests function as expected because the payload is limited to a single file.

see #72 for more info.

**Comment by david-chambers** [comment]
Thanks John for an explanation and closed issue #72.  I missed that.

**Comment by jgravois** [comment]
no worries.  I had the same question back in the day.
