### ISSUE TITLE
Support for ASP.NET CORE

### ISSUE THREAD

**Issue by Abexdatl** [Esri/resource-proxy#444]
We started to use ASP.NET CORE with the latest Esri Javascript fw (4.x) to build custom apps . 

This means the current implementation of the proxy page as request handler which is no more supported in ASP.NET CORE and replaced by middleware, won't work . 

Did you guys think about the change in Microsoft space ( classic vs CORE) and come up with a newer version of the proxy that works as a middleware ? If so when do you think that you can provide customers with a version that works on the ASP.NET CORE framework ?

Thanks,

**Comment by bsvensson** [comment]
Hi @Abexdatl - There are no current plans to create a resource-proxy that supports ASP.NET Core.

**Comment by Abexdatl** [comment]
Thanks for the response . I will run the request by esri support and see if esri can put an effort to support customers to use the products paid for with latest frameworks in the industry. 

To me the work is changing the request handler to a middleware and it wont be a terribly big work if there is willingness to do . 

But again thanks for your replay . 

Thanks,

**Comment by jgravois** [comment]
> I will run the request by esri support

@Abexdatl you already have a direct line to the team that maintains the project here and your issue is publicly searchable so others can chime in with a 👍  if it'd be helpful for them too.

 > the work is changing the request handler to a middleware

we've already received many great contributions from our user community to this open source project and would welcome one for this feature as well. @bsvensson is just being honest with you that we don't have the bandwidth internally to tackle the enhancement ourselves right now.

**Comment by dgwaldo** [comment]
Porting this to core would be nice. We plan on moving to core soon. Not to be picky or anything, but honestly the Proxy code for .Net is pretty messy. From a maintainability standpoint, logic comprehension, etc. Uncle Bob would not be pleased. A complete re-write when moving to .Net Core would be nice.

**Comment by jgravois** [comment]
> A complete re-write when moving to .Net Core would be nice.

pull requests welcome!

**Comment by dgwaldo** [comment]
Not to be disrespectful or anything :) But I'm not entirely aligned with ESRI's strategy here. The proxy code seems to be a key to many workflows utilizing ESRI technology. The proxy code is looks like it was not meaningfully engineer, rather arrived at... 

If the code had unit tests, and it appeared that ESRI had put their best foot forward so to speak (clean code). I'd hop right on it and work like a son of a gun to port this to core. :) 

ESRI is extracting large sums of money from the user base in licensing fees. To throw the proxy code out and "let the community support it" makes me frustrated. I spent the last two days fixing an issue in the proxy code. How about ESRI get themselves some bandwidth by buying some more software engineers. Dedicate one to cleaning up the proxy code. If this code is a reflection of the internals of other products, it explains much of the complaining about ESRI. I usually don't pay much attention to ESRI haters, but I'm right with them today :) I'd feel much different if the .net proxy code wasn't such a pile.

**Comment by Abexdatl** [comment]
When I asked the question initially , I was doing Angular /ArcGIS 4.x/ASP.NET CORE based development . It was a must for me ( in fact for any body who does serious stuff) to have a proxy page that works with ASP.NET CORE based project . Obviously the old stuff does not work with ASP.NET CORE based project because of the reasons I mentioned in the original post. 

The response that I got from esri was disappointing to say the least. Specially the " the proxy is community effort ..." is laughable to me.  

Anyway, we went a head and wrote our own middleware version of the old proxy page and most of the stuff is covered and will keep working on it to do further improvements . However, I should not be doing anything as far as the proxy page goes . Esri should have taken that initiative and provided for us.

**Comment by dgwaldo** [comment]
@redunuri I may be able to help you with that.. I've been contemplating dropping my proxy on github for core.

**Comment by redunuri** [comment]
@Abexdatl That will be great. Thank you so much for the response.

**Comment by redunuri** [comment]
@Abexdatl If you can let me know when you drop into github that will be great.

**Comment by dgwaldo** [comment]
@redunuri  I managed to get a version of the .net core proxy out tonight. Hope it helps.

https://github.com/dgwaldo/ags-resource-proxy

**Comment by redunuri** [comment]
@Abexdatl Thank you so much!

**Comment by dgwaldo** [comment]
@redunuri You keep referring to the wrong person in your posts.  Just an FYI.

**Comment by tomgruszowski** [comment]
ASP.NET Core is the default technology (.NET) for all greenfield projects, this should have official support. Practical .NET Core (i.e. v.2.x) has been out for over a year now, it's time Esri.

**Comment by deRightDirection** [comment]
yeah i think @redunuri, @tomgruszowski  & @Abexdatl do have a point here, we do have now the same issue, we need a proxy to support our workflow but our hosting server is Linux-based, so the only option with .Net which is left over, is .net core.

So it would be nice to see support from Esri here as well.

**Comment by dgwaldo** [comment]
@bsvensson  I'd be more than willing to turn over the .net core proxy project I created to ESRI. At this point I'm no longer working with the ESRI stack. Folks keep making pull requests and I have no access to ArcGIS Server to validate things. Would ESRI like to take over the project? https://github.com/dgwaldo/ags-resource-proxy

**Comment by bsvensson** [comment]
Hi @dgwaldo - thank you for the offer. And for creating the matching proxy for .Net Core.

Unfortunately the resource-proxy is currently in a maintenance mode with no active development. Even if we added your proxy for .Net Core to this repo, I don't think it would get any more love/testing, so probably best to leave as is.

**Comment by dgwaldo** [comment]
@bsvensson If it's in maintenance mode does that mean ESRI is working on another solution for the proxy issue? Like something baked into the core server product?

**Comment by bsvensson** [comment]
@dgwaldo - yes.  We mention some alternatives at https://github.com/Esri/resource-proxy#alternatives.  the first bullet is about how CORS, and how that can be used instead of proxy for some use cases.  More interesting is maybe the second bullet which is about the ArcGIS Online hosted proxy that's a better solution for many cases.

**Comment by capdragon** [comment]
I was very excited about using the alternate "ArcGIS Online hosted proxy". However, that only seems to work with ESRI services like geocoding and what not. For example, It doesn't seem like I can have a hosted feature table on AGOL and make REST calls to it within my APP using the ArcGIS online hosted proxy. This is the use case I'm trying to solve.

So I'm very much in favor of ESRI getting on board with contributing to the .NET CORE feature.

**Comment by bsvensson** [comment]
> I was very excited about using the alternate "ArcGIS Online hosted proxy". However, that only seems to work with ESRI services like geocoding and what not. For example, It doesn't seem like I can have a hosted feature table on AGOL and make REST calls to it within my APP using the ArcGIS online hosted proxy.

@capdragon - not sure if I understand, but you can use the "ArcGIS Online hosted proxy" to limit the usage by IP/URL for a private feature service.

For example, this private feature service (in a public webmap) can only be accessed when the app is hosted on codepen:
* Shows trees: https://codepen.io/bsvensson/pen/abOYYJX
* Does not show trees: https://www.arcgis.com/apps/Embed/index.html?webmap=287111a772a04f799d840bfcbfd52ce7

Not sure if that's the behavior you're looking for...

**Comment by capdragon** [comment]
> Not sure if that's the behavior you're looking for...

It is! Not sure how you did it, but when I register an application it only allows me to select from a list of services such as geocoding from a drop down. I can't simply specify a URL of a service I published.
![example](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/images/hosted-proxies.png)
How did you do it? Where were you able to specify the TREES service?

I'm following [these instructions](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/working-with-proxies/#arcgis-online-hosted-proxy) to no avail.

**Comment by bsvensson** [comment]
@capdragon This is documented (deep) in [https://doc.arcgis.com/en/arcgis-online/manage-data/add-items.htm](https://doc.arcgis.com/en/arcgis-online/manage-data/add-items.htm#ESRI_SECTION1_1A21D51E1AFC41EA9974209BD94E50C0), section "**Add items from the web**".  Step 5 is the important step.

For example:
* Log in to ArcGIS Online - https://www.arcgis.com
* Go to "Content"
* Click "Add Item"
* Click "From a URL"
* Enter the URL to a private service, e.g. https://services.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/Redlands_Trees/FeatureServer/0

This should prompt for your username and password...

**Comment by KevinKelchen** [comment]
Hi @bsvensson! 👋

A pleasure to bump into you on this thread. 🙂 

We're strongly considering using the self-hosted `resource-proxy` to get around CORS issues with a few our of clients' GIS admins.

Our Ionic/Cordova hybrid application for technical reasons is hosted at a hostname of `localhost` in the WebView of the native app shell. Some client GIS admins refuse to add `localhost` as an allowed origin ("security" reasons) to Portal instances or ArcGIS Server services. (Also, in the case of Portal and AGOL, it actually cannot be added due to UI rules that it's not a valid domain, so I think it'd require listing no origins at all in order to allow `localhost`.) This prevents us from using the ArcGIS API for JS to fetch data from their Portal instance or load operational data/tile layers within whatever webmaps they've created and display them in our application.

We were planning on hosting the `resource-proxy` and adding a configuration setting to our system for listing base URLs that need to be proxied for just those Portal instances and operational data/tile layers that don't allow `localhost` as an origin.

Given official documentation I've read about using the proxy as well as this repo's README I was a little surprised to find in this thread that `resource-proxy` is in maintenance mode and that the way forward for situations where CORS cannot be configured seems to be using a proxy in ArcGIS Online.

I was initially hopeful about this because that might mean not having to host the self-hosted `resource-proxy` and requests for all clients could just be forwarded to a single proxy in ArcGIS Online that could then forward the request to the client's GIS servers for these situations where Portal or ArcServer services don't allow `localhost`.

Looking into it given the helpful tips in this thread, I'm not sure the ArcGIS Online proxy can be configured with the same flexibility as the self-hosted `resource-proxy` to proxy traffic from the ArcGIS API for JS for any base URL we want (the Portal URL and just the restricted operational data/tile layer URLs). I could very well be missing something though. 😅

Given this context, would what be your recommendation for us?

Thanks, Bjorn! 😄

Kevin

**Comment by bsvensson** [comment]
Hi @KevinKelchen - thanks for reaching out, great questions. I'm not sure if your comment is specific to "ASP.NET CORE" (ie related to this specific github issue) as it seem to be more about the resource proxy in general. Which is fine :)

You're correct that this resource-proxy is in maintenance mode and not recommended.  There are better, and more secure, solutions available for most use cases.

Yes, the ArcGIS Online proxy does have less flexibility than something where you can control the code yourself. However, there might be some capabilities that you've overlooked. I know that not all of it is documented.

I think the best step forward for you is to connect directly.  @andygup will send you an email :)

**Comment by KevinKelchen** [comment]
Thanks so much for the reply, @bsvensson, and for that info!

We've since moved forward with using `resource-proxy` to get our client up and running so there's no hurry or anything for @andygup to reach out. 🙂

We felt that the .NET version of `resource-proxy` was a suitable fit for now given that our own server software uses similar technology (ASP.NET, .NET 4+, and is hosted in IIS). Within the next year or so we will probably be looking at migrating our server to .NET 5+ and a natural decision point will occur regarding how to proceed with `resource-proxy`. Hopefully the ArcGIS Online proxy will be able to meet our needs when the time comes.

Thanks again, Bjorn! 😀

Kevin

**Comment by khoanb83** [comment]
hi @bsvensson   . I hope Esri will support in ASP.NET CORE early.
Thanks
