### ISSUE TITLE
Add php-xml to requirements

### ISSUE THREAD

**Issue by sraimund** [Esri/resource-proxy#446]
I tried to install the PHP proxy 1.1.2 on a fresh Ubuntu 16.04 with Apache 2.4 and PHP 7.0 and got this error message when requesting http://[yourmachine]/PHP/proxy.php?ping:
`Call to undefined function xml_parser_create()`

To actually see the error message, I had to change `error_reporting(0)` to `error_reporting(1)` in proxy.php (otherwise just a blank screen appeared).

To make proxy.php work correctly, I had to install php-xml additionally:
`sudo apt-get install php-xml`

**Comment by bsvensson** [comment]
@sraimund - thanks for reporting.

`error_reporting(0)` turns off all error reporting, so this is on purpose - but not great if you're trying to figure out why nothing's working.  Setting it to to `error_reporting(1)` will report all errors, but if it's for debugging, it might also be useful to set it to `error_reporting(E_ALL)` - see http://php.net/manual/en/function.error-reporting.php and http://php.net/manual/en/errorfunc.constants.php for more details.

We/someone probably should do some more testing of this on Ubuntu...

Note: This sounds similar (but un-related) to the other PHP/Ubuntu issue about `proxy-verification.php` needing curl - #346.  Not sure if things have changed in Ubuntu since then (Ubuntu 14.04.3 LTS).
