### ISSUE TITLE
Modify Proxy (DotNet) to let Print Widget access secured services

### ISSUE THREAD

**Issue by LeoEger90** [Esri/resource-proxy#480]
Hi,
i need to modify the resource Proxy (DotNet) to print secured services widget without the Users being prompted to log in. 

https://community.esri.com/thread/213036-how-to-modify-our-proxy-so-it-allows-the-default-printing-service-to-print-secured-services

Anyone got an idea how to do this?

Best regards,
Leo

**Comment by bsvensson** [comment]
Hi @LeoEger90 
As you already mentioned in you geonet post, the preferred way is for either
(a) users to log in (so that the application can send along the tokens with the print request)
(b) use a custom print service that stores the credentials in the print service - see https://enterprise.arcgis.com/en/server/latest/create-web-apps/windows/printing-maps-that-contain-secured-services.htm

There's no plans to change the resource proxy to support the workflow you're asking about.

If you still want to do it, it would include the resource proxy introspecting the print request for specific services and somehow add the token inside that json before sending the print request to the print service.

Another option is for your application to handle this. Basically it would have to somehow get the tokens (maybe from a custom service) and use those. In this case, you could actually bypass the resource proxy for both viewing the layer and printing it.
