### ISSUE TITLE
Exchange Portal token for Server token does not work.

### ISSUE THREAD

**Issue by hmelendez** [Esri/resource-proxy#511]
I'm using oauth2 clientId and clientSecret to request a secure federated service from ArcGIS Server. The proxy generates the portal token using oauth2 then it exchanges that token for a server token but when the token is used in ArcGIS Server it returns an invalid token error. The following error appears in GIS Server log when in Debug mode:

DEBUG | Mar 28, 2019, 1:18:36 PM | Exception caught while validating token. Could not decrypt token. Token may not be valid.

DEBUG | Mar 28, 2019, 1:18:36 PM | Referer: https://localmapsdev.my.domain.com/viewer/?map=3561fcfe32714d2287f9aa498fbbcea0

[proxylog.txt](https://github.com/Esri/resource-proxy/files/3015955/proxylog.txt)

**Comment by hgonzago** [comment]
What version of the API are you using?

**Comment by hmelendez** [comment]
> What version of the API are you using?

ArcGIS Enterprise 10.6.1

**Comment by hgonzago** [comment]
I know that there were some fixes that we put in for 3.27. I don't know if this would apply in this scenario. Would you be able to check just to confirm?

**Comment by hmelendez** [comment]
> 3.27

I tested from a wab 2.11 that uses 3.27 and had the same Invalid Token error.
[proxylog.txt](https://github.com/Esri/resource-proxy/files/3027338/proxylog.txt)

**Comment by torrin47** [comment]
If I'm not mistaken, the premise of this ticket violates Esri's security model:

>  I'm using oauth2 clientId and clientSecret to request a secure federated service from ArcGIS Server.

But I'd like some confirmation from Esri, because the behavior of the proxy doesn't seem perfectly consistent with the documentation.  First, when you're using a clientID and clientSecret, you're implementing the App Login model:

https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/limitations-of-application-authentication/

not the named user model - so the reason @hmelendez is getting an invalid token error is a feature, not a bug - a token obtained via AppLogin isn't supposed to grant access to secured content items. That said, we're finding that an App Login actually does provide access to other content items owned by the user that registered the App - but does not provide access to federated services. That inconsistency is tantalizing, since before 10.3 and the introduction of Oauth2, we were able to proxy secure services via token authorization.  

https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/

So the question for Esri: is it still possible to use an embedded named user login in the resource proxy with Oauth2 (ArcGIS Enterprise 10.3 and up), and if so can you provide an example proxy.config snippet or is that unequivocally unsupported and will never be supported?
